/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "clk_generator_e.v:1" *)
module clk_generator_e(clk_32f, reset, clk_4f_e, clk_2f_e, clk_f_e);
  (* src = "clk_generator_e.v:12" *)
  reg _00_;
  (* src = "clk_generator_e.v:12" *)
  reg _01_;
  (* src = "clk_generator_e.v:12" *)
  reg _02_;
  (* src = "clk_generator_e.v:12" *)
  reg [3:0] _03_;
  (* src = "clk_generator_e.v:12" *)
  reg [2:0] _04_;
  (* src = "clk_generator_e.v:12" *)
  reg [1:0] _05_;
  (* src = "clk_generator_e.v:23" *)
  reg _06_;
  (* src = "clk_generator_e.v:23" *)
  reg _07_;
  (* src = "clk_generator_e.v:23" *)
  reg _08_;
  (* src = "clk_generator_e.v:23" *)
  reg [3:0] _09_;
  (* src = "clk_generator_e.v:23" *)
  reg [2:0] _10_;
  (* src = "clk_generator_e.v:23" *)
  reg [1:0] _11_;
  (* src = "clk_generator_e.v:13" *)
  wire _12_;
  (* src = "clk_generator_e.v:5" *)
  output clk_2f_e;
  reg clk_2f_e;
  (* src = "clk_generator_e.v:2" *)
  input clk_32f;
  (* src = "clk_generator_e.v:4" *)
  output clk_4f_e;
  reg clk_4f_e;
  (* src = "clk_generator_e.v:6" *)
  output clk_f_e;
  reg clk_f_e;
  (* src = "clk_generator_e.v:10" *)
  reg [3:0] conteo;
  (* src = "clk_generator_e.v:9" *)
  reg [2:0] conteo_2;
  (* src = "clk_generator_e.v:8" *)
  reg [1:0] conteo_4;
  (* src = "clk_generator_e.v:3" *)
  input reset;
  assign _12_ = ~(* src = "clk_generator_e.v:13" *) reset;
  always @* begin
    _04_ = conteo_2;
    _03_ = conteo;
    _02_ = clk_f_e;
    _05_ = conteo_4;
    _01_ = clk_4f_e;
    _00_ = clk_2f_e;
    (* src = "clk_generator_e.v:13" *)
    casez (_12_)
      /* src = "clk_generator_e.v:13" */
      1'h1:
        begin
          _05_ = 2'h3;
          _04_ = 3'h7;
          _03_ = 4'hf;
          _01_ = 1'h0;
          _00_ = 1'h0;
          _02_ = 1'h0;
        end
      default:
          /* empty */;
    endcase
  end
  always @* begin
      conteo_2 <= _04_;
      conteo <= _03_;
      clk_f_e <= _02_;
      conteo_4 <= _05_;
      clk_4f_e <= _01_;
      clk_2f_e <= _00_;
  end
  always @* begin
    _10_ = conteo_2;
    _09_ = conteo;
    _08_ = clk_f_e;
    _11_ = conteo_4;
    _07_ = clk_4f_e;
    _06_ = clk_2f_e;
    (* src = "clk_generator_e.v:24" *)
    casez (conteo_4)
      /* src = "clk_generator_e.v:25" */
      2'h0:
          _11_ = 2'h1;
      /* src = "clk_generator_e.v:26" */
      2'h1:
          _11_ = 2'h2;
      /* src = "clk_generator_e.v:27" */
      2'h2:
          _11_ = 2'h3;
      /* src = "clk_generator_e.v:28" */
      2'h3:
        begin
          _11_ = 2'h0;
          (* src = "clk_generator_e.v:31" *)
          casez (clk_4f_e)
            /* src = "clk_generator_e.v:32" */
            1'h0:
                _07_ = 1'h1;
            /* src = "clk_generator_e.v:33" */
            1'h1:
                _07_ = 1'h0;
            default:
                /* empty */;
          endcase
        end
      default:
          /* empty */;
    endcase
    (* src = "clk_generator_e.v:37" *)
    casez (conteo_2)
      /* src = "clk_generator_e.v:38" */
      3'h0:
          _10_ = 3'h1;
      /* src = "clk_generator_e.v:39" */
      3'h1:
          _10_ = 3'h2;
      /* src = "clk_generator_e.v:40" */
      3'h2:
          _10_ = 3'h3;
      /* src = "clk_generator_e.v:41" */
      3'h3:
          _10_ = 3'h4;
      /* src = "clk_generator_e.v:42" */
      3'h4:
          _10_ = 3'h5;
      /* src = "clk_generator_e.v:43" */
      3'h5:
          _10_ = 3'h6;
      /* src = "clk_generator_e.v:44" */
      3'h6:
          _10_ = 3'h7;
      /* src = "clk_generator_e.v:45" */
      3'h7:
        begin
          _10_ = 3'h0;
          (* src = "clk_generator_e.v:48" *)
          casez (clk_2f_e)
            /* src = "clk_generator_e.v:49" */
            1'h0:
                _06_ = 1'h1;
            /* src = "clk_generator_e.v:50" */
            1'h1:
                _06_ = 1'h0;
            default:
                /* empty */;
          endcase
        end
      default:
          /* empty */;
    endcase
    (* src = "clk_generator_e.v:54" *)
    casez (conteo)
      /* src = "clk_generator_e.v:55" */
      4'h0:
          _09_ = 4'h1;
      /* src = "clk_generator_e.v:56" */
      4'h1:
          _09_ = 4'h2;
      /* src = "clk_generator_e.v:57" */
      4'h2:
          _09_ = 4'h3;
      /* src = "clk_generator_e.v:58" */
      4'h3:
          _09_ = 4'h4;
      /* src = "clk_generator_e.v:59" */
      4'h4:
          _09_ = 4'h5;
      /* src = "clk_generator_e.v:60" */
      4'h5:
          _09_ = 4'h6;
      /* src = "clk_generator_e.v:61" */
      4'h6:
          _09_ = 4'h7;
      /* src = "clk_generator_e.v:62" */
      4'h7:
          _09_ = 4'h8;
      /* src = "clk_generator_e.v:63" */
      4'h8:
          _09_ = 4'h9;
      /* src = "clk_generator_e.v:64" */
      4'h9:
          _09_ = 4'ha;
      /* src = "clk_generator_e.v:65" */
      4'ha:
          _09_ = 4'hb;
      /* src = "clk_generator_e.v:66" */
      4'hb:
          _09_ = 4'hc;
      /* src = "clk_generator_e.v:67" */
      4'hc:
          _09_ = 4'hd;
      /* src = "clk_generator_e.v:68" */
      4'hd:
          _09_ = 4'he;
      /* src = "clk_generator_e.v:69" */
      4'he:
          _09_ = 4'hf;
      /* src = "clk_generator_e.v:70" */
      4'hf:
        begin
          _09_ = 4'h0;
          (* src = "clk_generator_e.v:73" *)
          casez (clk_f_e)
            /* src = "clk_generator_e.v:74" */
            1'h0:
                _08_ = 1'h1;
            /* src = "clk_generator_e.v:75" */
            1'h1:
                _08_ = 1'h0;
            default:
                /* empty */;
          endcase
        end
      default:
          /* empty */;
    endcase
  end
  always @(posedge clk_32f) begin
      conteo_2 <= _10_;
      conteo <= _09_;
      clk_f_e <= _08_;
      conteo_4 <= _11_;
      clk_4f_e <= _07_;
      clk_2f_e <= _06_;
  end
endmodule
