/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "clk_generator_e.v:1" *)
module clk_generator_e(clk_32f, reset, clk_4f_e, clk_2f_e, clk_f_e);
  (* src = "clk_generator_e.v:11" *)
  reg _00_;
  (* src = "clk_generator_e.v:11" *)
  reg _01_;
  (* src = "clk_generator_e.v:11" *)
  reg _02_;
  (* src = "clk_generator_e.v:11" *)
  reg _03_;
  (* src = "clk_generator_e.v:11" *)
  reg _04_;
  (* src = "clk_generator_e.v:21" *)
  reg _05_;
  (* src = "clk_generator_e.v:36" *)
  reg _06_;
  (* src = "clk_generator_e.v:31" *)
  reg _07_;
  (* src = "clk_generator_e.v:26" *)
  reg _08_;
  (* src = "clk_generator_e.v:41" *)
  reg _09_;
  (* src = "clk_generator_e.v:27" *)
  wire _10_;
  (* src = "clk_generator_e.v:28" *)
  wire _11_;
  (* src = "clk_generator_e.v:32" *)
  wire _12_;
  (* src = "clk_generator_e.v:32" *)
  wire _13_;
  (* src = "clk_generator_e.v:33" *)
  wire _14_;
  (* src = "clk_generator_e.v:33" *)
  wire _15_;
  (* src = "clk_generator_e.v:37" *)
  wire _16_;
  (* src = "clk_generator_e.v:37" *)
  wire _17_;
  (* src = "clk_generator_e.v:37" *)
  wire _18_;
  (* src = "clk_generator_e.v:38" *)
  wire _19_;
  (* src = "clk_generator_e.v:38" *)
  wire _20_;
  (* src = "clk_generator_e.v:38" *)
  wire _21_;
  (* src = "clk_generator_e.v:42" *)
  wire _22_;
  (* src = "clk_generator_e.v:42" *)
  wire _23_;
  (* src = "clk_generator_e.v:42" *)
  wire _24_;
  (* src = "clk_generator_e.v:42" *)
  wire _25_;
  (* src = "clk_generator_e.v:43" *)
  wire _26_;
  (* src = "clk_generator_e.v:43" *)
  wire _27_;
  (* src = "clk_generator_e.v:43" *)
  wire _28_;
  (* src = "clk_generator_e.v:43" *)
  wire _29_;
  (* src = "clk_generator_e.v:12" *)
  wire _30_;
  (* src = "clk_generator_e.v:23" *)
  wire _31_;
  (* src = "clk_generator_e.v:27" *)
  wire _32_;
  (* src = "clk_generator_e.v:27" *)
  wire _33_;
  (* src = "clk_generator_e.v:28" *)
  wire _34_;
  (* src = "clk_generator_e.v:32" *)
  wire _35_;
  (* src = "clk_generator_e.v:32" *)
  wire _36_;
  (* src = "clk_generator_e.v:32" *)
  wire _37_;
  (* src = "clk_generator_e.v:33" *)
  wire _38_;
  (* src = "clk_generator_e.v:33" *)
  wire _39_;
  (* src = "clk_generator_e.v:37" *)
  wire _40_;
  (* src = "clk_generator_e.v:37" *)
  wire _41_;
  (* src = "clk_generator_e.v:37" *)
  wire _42_;
  (* src = "clk_generator_e.v:37" *)
  wire _43_;
  (* src = "clk_generator_e.v:38" *)
  wire _44_;
  (* src = "clk_generator_e.v:38" *)
  wire _45_;
  (* src = "clk_generator_e.v:38" *)
  wire _46_;
  (* src = "clk_generator_e.v:42" *)
  wire _47_;
  (* src = "clk_generator_e.v:42" *)
  wire _48_;
  (* src = "clk_generator_e.v:42" *)
  wire _49_;
  (* src = "clk_generator_e.v:42" *)
  wire _50_;
  (* src = "clk_generator_e.v:42" *)
  wire _51_;
  (* src = "clk_generator_e.v:43" *)
  wire _52_;
  (* src = "clk_generator_e.v:43" *)
  wire _53_;
  (* src = "clk_generator_e.v:43" *)
  wire _54_;
  (* src = "clk_generator_e.v:43" *)
  wire _55_;
  (* src = "clk_generator_e.v:8" *)
  reg clk_16f_e;
  (* src = "clk_generator_e.v:5" *)
  output clk_2f_e;
  reg clk_2f_e;
  (* src = "clk_generator_e.v:2" *)
  input clk_32f;
  (* src = "clk_generator_e.v:4" *)
  output clk_4f_e;
  reg clk_4f_e;
  (* src = "clk_generator_e.v:9" *)
  reg clk_8f_e;
  (* src = "clk_generator_e.v:6" *)
  output clk_f_e;
  reg clk_f_e;
  (* src = "clk_generator_e.v:3" *)
  input reset;
  assign _51_ = ~(* src = "clk_generator_e.v:42" *) clk_f_e;
  assign _52_ = ~(* src = "clk_generator_e.v:43" *) clk_16f_e;
  assign _53_ = ~(* src = "clk_generator_e.v:43" *) clk_8f_e;
  assign _54_ = ~(* src = "clk_generator_e.v:43" *) clk_4f_e;
  assign _55_ = ~(* src = "clk_generator_e.v:43" *) clk_2f_e;
  assign _30_ = ~(* src = "clk_generator_e.v:12" *) reset;
  assign _19_ = _44_ &(* src = "clk_generator_e.v:38" *)  _45_;
  assign _21_ = _20_ &(* src = "clk_generator_e.v:38" *)  clk_2f_e;
  assign _23_ = _22_ &(* src = "clk_generator_e.v:42" *)  _49_;
  assign _25_ = _24_ &(* src = "clk_generator_e.v:42" *)  _51_;
  assign _28_ = _27_ &(* src = "clk_generator_e.v:43" *)  _55_;
  assign _29_ = _28_ &(* src = "clk_generator_e.v:43" *)  clk_f_e;
  assign _11_ = _34_ &(* src = "clk_generator_e.v:28" *)  clk_8f_e;
  assign _15_ = _14_ &(* src = "clk_generator_e.v:33" *)  clk_4f_e;
  always @* begin
    _03_ = clk_8f_e;
    _04_ = clk_f_e;
    _00_ = clk_16f_e;
    _02_ = clk_4f_e;
    _01_ = clk_2f_e;
    (* src = "clk_generator_e.v:12" *)
    casez (_30_)
      /* src = "clk_generator_e.v:12" */
      1'h1:
        begin
          _00_ = 1'h0;
          _03_ = 1'h0;
          _02_ = 1'h0;
          _01_ = 1'h0;
          _04_ = 1'h0;
        end
      default:
          /* empty */;
    endcase
  end
  always @(posedge clk_32f) begin
      clk_8f_e <= _03_;
      clk_f_e <= _04_;
      clk_16f_e <= _00_;
      clk_4f_e <= _02_;
      clk_2f_e <= _01_;
  end
  always @* begin
    _05_ = clk_16f_e;
    (* src = "clk_generator_e.v:22" *)
    casez (clk_16f_e)
      /* src = "clk_generator_e.v:22" */
      1'h1:
          _05_ = 1'h0;
      /* src = "clk_generator_e.v:23" */
      default:
          (* src = "clk_generator_e.v:23" *)
          casez (_31_)
            /* src = "clk_generator_e.v:23" */
            1'h1:
                _05_ = 1'h1;
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk_32f) begin
      clk_16f_e <= _05_;
  end
  always @* begin
    _08_ = clk_8f_e;
    (* src = "clk_generator_e.v:27" *)
    casez (_10_)
      /* src = "clk_generator_e.v:27" */
      1'h1:
          _08_ = 1'h1;
      /* src = "clk_generator_e.v:28" */
      default:
          (* src = "clk_generator_e.v:28" *)
          casez (_11_)
            /* src = "clk_generator_e.v:28" */
            1'h1:
                _08_ = 1'h0;
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk_32f) begin
      clk_8f_e <= _08_;
  end
  always @* begin
    _07_ = clk_4f_e;
    (* src = "clk_generator_e.v:32" *)
    casez (_13_)
      /* src = "clk_generator_e.v:32" */
      1'h1:
          _07_ = 1'h1;
      /* src = "clk_generator_e.v:33" */
      default:
          (* src = "clk_generator_e.v:33" *)
          casez (_15_)
            /* src = "clk_generator_e.v:33" */
            1'h1:
                _07_ = 1'h0;
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk_32f) begin
      clk_4f_e <= _07_;
  end
  always @* begin
    _06_ = clk_2f_e;
    (* src = "clk_generator_e.v:37" *)
    casez (_18_)
      /* src = "clk_generator_e.v:37" */
      1'h1:
          _06_ = 1'h1;
      /* src = "clk_generator_e.v:38" */
      default:
          (* src = "clk_generator_e.v:38" *)
          casez (_21_)
            /* src = "clk_generator_e.v:38" */
            1'h1:
                _06_ = 1'h0;
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk_32f) begin
      clk_2f_e <= _06_;
  end
  always @* begin
    _09_ = clk_f_e;
    (* src = "clk_generator_e.v:42" *)
    casez (_25_)
      /* src = "clk_generator_e.v:42" */
      1'h1:
          _09_ = 1'h1;
      /* src = "clk_generator_e.v:43" */
      default:
          (* src = "clk_generator_e.v:43" *)
          casez (_29_)
            /* src = "clk_generator_e.v:43" */
            1'h1:
                _09_ = 1'h0;
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk_32f) begin
      clk_f_e <= _09_;
  end
  assign _50_ = _55_;
  assign _49_ = _54_;
  assign _48_ = _53_;
  assign _47_ = _52_;
  assign _46_ = _54_;
  assign _45_ = _53_;
  assign _44_ = _52_;
  assign _43_ = _55_;
  assign _42_ = _54_;
  assign _41_ = _53_;
  assign _40_ = _52_;
  assign _39_ = _53_;
  assign _38_ = _52_;
  assign _37_ = _54_;
  assign _36_ = _53_;
  assign _35_ = _52_;
  assign _34_ = _52_;
  assign _33_ = _53_;
  assign _32_ = _52_;
  assign _31_ = _52_;
  assign _26_ = _19_;
  assign _16_ = _19_;
  assign _14_ = _19_;
  assign _12_ = _19_;
  assign _22_ = _19_;
  assign _10_ = _19_;
  assign _20_ = _27_;
  assign _13_ = _23_;
  assign _27_ = _23_;
  assign _17_ = _23_;
  assign _18_ = _28_;
  assign _24_ = _28_;
endmodule
