/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "bits8_32word_e.v:1" *)
module bits8_32word_e(clk_4f_e, reset, valid_in, Data_in, valid_out_e, Data_out_e);
  (* src = "bits8_32word_e.v:14" *)
  reg [31:0] _00_;
  (* src = "bits8_32word_e.v:14" *)
  reg [1:0] _01_;
  (* src = "bits8_32word_e.v:14" *)
  reg _02_;
  (* src = "bits8_32word_e.v:14" *)
  reg [31:0] _03_;
  (* src = "bits8_32word_e.v:14" *)
  reg _04_;
  (* src = "bits8_32word_e.v:14" *)
  reg _05_;
  (* src = "bits8_32word_e.v:25" *)
  reg [31:0] _06_;
  (* src = "bits8_32word_e.v:25" *)
  reg [1:0] _07_;
  (* src = "bits8_32word_e.v:25" *)
  reg _08_;
  (* src = "bits8_32word_e.v:25" *)
  reg [31:0] _09_;
  (* src = "bits8_32word_e.v:25" *)
  reg _10_;
  (* src = "bits8_32word_e.v:25" *)
  reg _11_;
  (* src = "bits8_32word_e.v:15" *)
  wire _12_;
  (* src = "bits8_32word_e.v:5" *)
  input [7:0] Data_in;
  (* src = "bits8_32word_e.v:7" *)
  output [31:0] Data_out_e;
  reg [31:0] Data_out_e;
  (* src = "bits8_32word_e.v:2" *)
  input clk_4f_e;
  (* src = "bits8_32word_e.v:9" *)
  reg [1:0] contador;
  (* src = "bits8_32word_e.v:12" *)
  reg down;
  (* src = "bits8_32word_e.v:10" *)
  reg [31:0] memoria;
  (* src = "bits8_32word_e.v:3" *)
  input reset;
  (* src = "bits8_32word_e.v:11" *)
  reg valid;
  (* src = "bits8_32word_e.v:4" *)
  input valid_in;
  (* src = "bits8_32word_e.v:6" *)
  output valid_out_e;
  reg valid_out_e;
  assign _12_ = ~(* src = "bits8_32word_e.v:15" *) reset;
  always @* begin
    _01_ = contador;
    _05_ = valid_out_e;
    _00_ = Data_out_e;
    _04_ = valid;
    _02_ = down;
    _03_ = memoria;
    (* src = "bits8_32word_e.v:15" *)
    casez (_12_)
      /* src = "bits8_32word_e.v:15" */
      1'h1:
        begin
          _05_ = 1'h0;
          _00_ = 32'd0;
          _01_ = 2'h3;
          _03_ = 32'd0;
          _04_ = 1'h0;
          _02_ = 1'h0;
        end
      default:
          /* empty */;
    endcase
  end
  always @* begin
      contador <= _01_;
      valid_out_e <= _05_;
      Data_out_e <= _00_;
      valid <= _04_;
      down <= _02_;
      memoria <= _03_;
  end
  always @* begin
    _07_ = contador;
    _11_ = valid_out_e;
    _06_ = Data_out_e;
    _10_ = valid;
    _08_ = down;
    _09_ = memoria;
    (* src = "bits8_32word_e.v:26" *)
    casez (valid_in)
      /* src = "bits8_32word_e.v:26" */
      1'h1:
          (* src = "bits8_32word_e.v:27" *)
          casez (contador)
            /* src = "bits8_32word_e.v:28" */
            2'h0:
              begin
                _11_ = valid;
                _06_ = memoria;
                _09_ = { Data_in, 24'h000000 };
                _07_ = 2'h1;
              end
            /* src = "bits8_32word_e.v:35" */
            2'h1:
              begin
                _09_ = { memoria[31:24], Data_in, 16'h0000 };
                _07_ = 2'h2;
              end
            /* src = "bits8_32word_e.v:40" */
            2'h2:
              begin
                _09_ = { memoria[31:16], Data_in, 8'h00 };
                _07_ = 2'h3;
              end
            /* src = "bits8_32word_e.v:45" */
            2'h3:
              begin
                _09_ = { memoria[31:8], Data_in };
                _10_ = 1'h1;
                _07_ = 2'h0;
                _08_ = 1'h0;
              end
            default:
                /* empty */;
          endcase
      /* src = "bits8_32word_e.v:54" */
      default:
          (* src = "bits8_32word_e.v:55" *)
          casez (contador)
            /* src = "bits8_32word_e.v:56" */
            2'h0:
              begin
                _11_ = valid;
                _06_ = memoria;
                (* src = "bits8_32word_e.v:60" *)
                casez (down)
                  /* src = "bits8_32word_e.v:60" */
                  1'h1:
                      _07_ = 2'h0;
                  /* src = "bits8_32word_e.v:61" */
                  default:
                      _07_ = 2'h1;
                endcase
              end
            /* src = "bits8_32word_e.v:63" */
            2'h1:
                _07_ = 2'h2;
            /* src = "bits8_32word_e.v:64" */
            2'h2:
                _07_ = 2'h3;
            /* src = "bits8_32word_e.v:65" */
            2'h3:
              begin
                _09_ = 32'd0;
                _10_ = 1'h0;
                _07_ = 2'h0;
                _08_ = 1'h1;
              end
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk_4f_e) begin
      contador <= _07_;
      valid_out_e <= _11_;
      Data_out_e <= _06_;
      valid <= _10_;
      down <= _08_;
      memoria <= _09_;
  end
endmodule

(* src = "byte_striping_e.v:1" *)
module byte_striping_e(clk_2f_e, reset, valid_in, Data_in, valid_0_c, lane_0_c, valid_1_c, lane_1_c);
  (* src = "byte_striping_e.v:13" *)
  reg _00_;
  (* src = "byte_striping_e.v:13" *)
  reg [31:0] _01_;
  (* src = "byte_striping_e.v:13" *)
  reg [31:0] _02_;
  (* src = "byte_striping_e.v:13" *)
  reg _03_;
  (* src = "byte_striping_e.v:13" *)
  reg _04_;
  (* src = "byte_striping_e.v:23" *)
  reg _05_;
  (* src = "byte_striping_e.v:23" *)
  reg [31:0] _06_;
  (* src = "byte_striping_e.v:23" *)
  reg [31:0] _07_;
  (* src = "byte_striping_e.v:23" *)
  reg _08_;
  (* src = "byte_striping_e.v:23" *)
  reg _09_;
  (* src = "byte_striping_e.v:14" *)
  wire _10_;
  (* src = "byte_striping_e.v:43" *)
  wire _11_;
  (* src = "byte_striping_e.v:5" *)
  input [31:0] Data_in;
  (* src = "byte_striping_e.v:2" *)
  input clk_2f_e;
  (* src = "byte_striping_e.v:11" *)
  reg contador;
  (* src = "byte_striping_e.v:7" *)
  output [31:0] lane_0_c;
  reg [31:0] lane_0_c;
  (* src = "byte_striping_e.v:9" *)
  output [31:0] lane_1_c;
  reg [31:0] lane_1_c;
  (* src = "byte_striping_e.v:3" *)
  input reset;
  (* src = "byte_striping_e.v:6" *)
  output valid_0_c;
  reg valid_0_c;
  (* src = "byte_striping_e.v:8" *)
  output valid_1_c;
  reg valid_1_c;
  (* src = "byte_striping_e.v:4" *)
  input valid_in;
  assign _10_ = ~(* src = "byte_striping_e.v:14" *) reset;
  assign _11_ = ~(* src = "byte_striping_e.v:43" *) valid_0_c;
  always @* begin
    _04_ = valid_1_c;
    _02_ = lane_1_c;
    _00_ = contador;
    _03_ = valid_0_c;
    _01_ = lane_0_c;
    (* src = "byte_striping_e.v:14" *)
    casez (_10_)
      /* src = "byte_striping_e.v:14" */
      1'h1:
        begin
          _03_ = 1'h0;
          _01_ = 32'd0;
          _04_ = 1'h0;
          _02_ = 32'd0;
          _00_ = 1'h0;
        end
      default:
          /* empty */;
    endcase
  end
  always @* begin
      valid_1_c <= _04_;
      lane_1_c <= _02_;
      contador <= _00_;
      valid_0_c <= _03_;
      lane_0_c <= _01_;
  end
  always @* begin
    _09_ = valid_1_c;
    _07_ = lane_1_c;
    _05_ = contador;
    _08_ = valid_0_c;
    _06_ = lane_0_c;
    (* src = "byte_striping_e.v:24" *)
    casez (valid_in)
      /* src = "byte_striping_e.v:24" */
      1'h1:
          (* src = "byte_striping_e.v:25" *)
          casez (contador)
            /* src = "byte_striping_e.v:26" */
            1'h0:
              begin
                _05_ = 1'h1;
                _06_ = Data_in;
                _08_ = 1'h1;
              end
            /* src = "byte_striping_e.v:32" */
            1'h1:
              begin
                _05_ = 1'h0;
                _07_ = Data_in;
                _09_ = 1'h1;
              end
            default:
                /* empty */;
          endcase
      /* src = "byte_striping_e.v:40" */
      default:
        begin
          _08_ = 1'h0;
          _06_ = 32'd0;
          (* src = "byte_striping_e.v:43" *)
          casez (_11_)
            /* src = "byte_striping_e.v:43" */
            1'h1:
              begin
                _07_ = 32'd0;
                _09_ = 1'h0;
              end
            default:
                /* empty */;
          endcase
        end
    endcase
  end
  always @(posedge clk_2f_e) begin
      valid_1_c <= _09_;
      lane_1_c <= _07_;
      contador <= _05_;
      valid_0_c <= _08_;
      lane_0_c <= _06_;
  end
endmodule

(* src = "byte_un_striping_e.v:1" *)
module byte_un_striping_e(clk_2f_e, reset, valid_0, lane_0, valid_1, lane_1, valid_out_e, Data_out_e);
  (* src = "byte_un_striping_e.v:13" *)
  reg [31:0] _0_;
  (* src = "byte_un_striping_e.v:13" *)
  reg _1_;
  (* src = "byte_un_striping_e.v:13" *)
  reg _2_;
  (* src = "byte_un_striping_e.v:21" *)
  reg [31:0] _3_;
  (* src = "byte_un_striping_e.v:21" *)
  reg _4_;
  (* src = "byte_un_striping_e.v:21" *)
  reg _5_;
  (* src = "byte_un_striping_e.v:14" *)
  wire _6_;
  (* src = "byte_un_striping_e.v:9" *)
  output [31:0] Data_out_e;
  reg [31:0] Data_out_e;
  (* src = "byte_un_striping_e.v:2" *)
  input clk_2f_e;
  (* src = "byte_un_striping_e.v:11" *)
  reg contador;
  (* src = "byte_un_striping_e.v:5" *)
  input [31:0] lane_0;
  (* src = "byte_un_striping_e.v:7" *)
  input [31:0] lane_1;
  (* src = "byte_un_striping_e.v:3" *)
  input reset;
  (* src = "byte_un_striping_e.v:4" *)
  input valid_0;
  (* src = "byte_un_striping_e.v:6" *)
  input valid_1;
  (* src = "byte_un_striping_e.v:8" *)
  output valid_out_e;
  reg valid_out_e;
  assign _6_ = ~(* src = "byte_un_striping_e.v:14" *) reset;
  always @* begin
    _1_ = contador;
    _2_ = valid_out_e;
    _0_ = Data_out_e;
    (* src = "byte_un_striping_e.v:14" *)
    casez (_6_)
      /* src = "byte_un_striping_e.v:14" */
      1'h1:
        begin
          _2_ = 1'h0;
          _0_ = 32'd0;
          _1_ = 1'h1;
        end
      default:
          /* empty */;
    endcase
  end
  always @* begin
      contador <= _1_;
      valid_out_e <= _2_;
      Data_out_e <= _0_;
  end
  always @* begin
    _4_ = contador;
    _5_ = valid_out_e;
    _3_ = Data_out_e;
    (* src = "byte_un_striping_e.v:22" *)
    casez (contador)
      /* src = "byte_un_striping_e.v:23" */
      1'h0:
          (* src = "byte_un_striping_e.v:25" *)
          casez (valid_0)
            /* src = "byte_un_striping_e.v:25" */
            1'h1:
              begin
                _4_ = 1'h1;
                _5_ = 1'h1;
                _3_ = lane_0;
              end
            /* src = "byte_un_striping_e.v:30" */
            default:
              begin
                _4_ = 1'h1;
                _5_ = 1'h0;
                _3_ = 32'd0;
              end
          endcase
      /* src = "byte_un_striping_e.v:36" */
      1'h1:
          (* src = "byte_un_striping_e.v:38" *)
          casez (valid_1)
            /* src = "byte_un_striping_e.v:38" */
            1'h1:
              begin
                _4_ = 1'h0;
                _5_ = 1'h1;
                _3_ = lane_1;
              end
            /* src = "byte_un_striping_e.v:43" */
            default:
              begin
                _4_ = 1'h0;
                _5_ = 1'h0;
                _3_ = 32'd0;
              end
          endcase
      default:
          /* empty */;
    endcase
  end
  always @(posedge clk_2f_e) begin
      contador <= _4_;
      valid_out_e <= _5_;
      Data_out_e <= _3_;
  end
endmodule

(* src = "clk_generator_e.v:1" *)
module clk_generator_e(clk_32f, reset, clk_4f_e, clk_2f_e, clk_f_c);
  (* src = "clk_generator_e.v:12" *)
  reg _00_;
  (* src = "clk_generator_e.v:12" *)
  reg _01_;
  (* src = "clk_generator_e.v:12" *)
  reg _02_;
  (* src = "clk_generator_e.v:12" *)
  reg [3:0] _03_;
  (* src = "clk_generator_e.v:12" *)
  reg [2:0] _04_;
  (* src = "clk_generator_e.v:12" *)
  reg [1:0] _05_;
  (* src = "clk_generator_e.v:23" *)
  reg _06_;
  (* src = "clk_generator_e.v:23" *)
  reg _07_;
  (* src = "clk_generator_e.v:23" *)
  reg _08_;
  (* src = "clk_generator_e.v:23" *)
  reg [3:0] _09_;
  (* src = "clk_generator_e.v:23" *)
  reg [2:0] _10_;
  (* src = "clk_generator_e.v:23" *)
  reg [1:0] _11_;
  (* src = "clk_generator_e.v:13" *)
  wire _12_;
  (* src = "clk_generator_e.v:5" *)
  output clk_2f_e;
  reg clk_2f_e;
  (* src = "clk_generator_e.v:2" *)
  input clk_32f;
  (* src = "clk_generator_e.v:4" *)
  output clk_4f_e;
  reg clk_4f_e;
  (* src = "clk_generator_e.v:6" *)
  output clk_f_c;
  reg clk_f_c;
  (* src = "clk_generator_e.v:10" *)
  reg [3:0] conteo;
  (* src = "clk_generator_e.v:9" *)
  reg [2:0] conteo_2;
  (* src = "clk_generator_e.v:8" *)
  reg [1:0] conteo_4;
  (* src = "clk_generator_e.v:3" *)
  input reset;
  assign _12_ = ~(* src = "clk_generator_e.v:13" *) reset;
  always @* begin
    _00_ = clk_2f_e;
    _01_ = clk_4f_e;
    _02_ = clk_f_c;
    _05_ = conteo_4;
    _04_ = conteo_2;
    _03_ = conteo;
    (* src = "clk_generator_e.v:13" *)
    casez (_12_)
      /* src = "clk_generator_e.v:13" */
      1'h1:
        begin
          _05_ = 2'h3;
          _04_ = 3'h7;
          _03_ = 4'hf;
          _01_ = 1'h0;
          _00_ = 1'h0;
          _02_ = 1'h0;
        end
      default:
          /* empty */;
    endcase
  end
  always @* begin
      clk_2f_e <= _00_;
      clk_4f_e <= _01_;
      clk_f_c <= _02_;
      conteo_4 <= _05_;
      conteo_2 <= _04_;
      conteo <= _03_;
  end
  always @* begin
    _06_ = clk_2f_e;
    _07_ = clk_4f_e;
    _08_ = clk_f_c;
    _11_ = conteo_4;
    _10_ = conteo_2;
    _09_ = conteo;
    (* src = "clk_generator_e.v:24" *)
    casez (conteo_4)
      /* src = "clk_generator_e.v:25" */
      2'h0:
          _11_ = 2'h1;
      /* src = "clk_generator_e.v:26" */
      2'h1:
          _11_ = 2'h2;
      /* src = "clk_generator_e.v:27" */
      2'h2:
          _11_ = 2'h3;
      /* src = "clk_generator_e.v:28" */
      2'h3:
        begin
          _11_ = 2'h0;
          (* src = "clk_generator_e.v:31" *)
          casez (clk_4f_e)
            /* src = "clk_generator_e.v:32" */
            1'h0:
                _07_ = 1'h1;
            /* src = "clk_generator_e.v:33" */
            1'h1:
                _07_ = 1'h0;
            default:
                /* empty */;
          endcase
        end
      default:
          /* empty */;
    endcase
    (* src = "clk_generator_e.v:37" *)
    casez (conteo_2)
      /* src = "clk_generator_e.v:38" */
      3'h0:
          _10_ = 3'h1;
      /* src = "clk_generator_e.v:39" */
      3'h1:
          _10_ = 3'h2;
      /* src = "clk_generator_e.v:40" */
      3'h2:
          _10_ = 3'h3;
      /* src = "clk_generator_e.v:41" */
      3'h3:
          _10_ = 3'h4;
      /* src = "clk_generator_e.v:42" */
      3'h4:
          _10_ = 3'h5;
      /* src = "clk_generator_e.v:43" */
      3'h5:
          _10_ = 3'h6;
      /* src = "clk_generator_e.v:44" */
      3'h6:
          _10_ = 3'h7;
      /* src = "clk_generator_e.v:45" */
      3'h7:
        begin
          _10_ = 3'h0;
          (* src = "clk_generator_e.v:48" *)
          casez (clk_2f_e)
            /* src = "clk_generator_e.v:49" */
            1'h0:
                _06_ = 1'h1;
            /* src = "clk_generator_e.v:50" */
            1'h1:
                _06_ = 1'h0;
            default:
                /* empty */;
          endcase
        end
      default:
          /* empty */;
    endcase
    (* src = "clk_generator_e.v:54" *)
    casez (conteo)
      /* src = "clk_generator_e.v:55" */
      4'h0:
          _09_ = 4'h1;
      /* src = "clk_generator_e.v:56" */
      4'h1:
          _09_ = 4'h2;
      /* src = "clk_generator_e.v:57" */
      4'h2:
          _09_ = 4'h3;
      /* src = "clk_generator_e.v:58" */
      4'h3:
          _09_ = 4'h4;
      /* src = "clk_generator_e.v:59" */
      4'h4:
          _09_ = 4'h5;
      /* src = "clk_generator_e.v:60" */
      4'h5:
          _09_ = 4'h6;
      /* src = "clk_generator_e.v:61" */
      4'h6:
          _09_ = 4'h7;
      /* src = "clk_generator_e.v:62" */
      4'h7:
          _09_ = 4'h8;
      /* src = "clk_generator_e.v:63" */
      4'h8:
          _09_ = 4'h9;
      /* src = "clk_generator_e.v:64" */
      4'h9:
          _09_ = 4'ha;
      /* src = "clk_generator_e.v:65" */
      4'ha:
          _09_ = 4'hb;
      /* src = "clk_generator_e.v:66" */
      4'hb:
          _09_ = 4'hc;
      /* src = "clk_generator_e.v:67" */
      4'hc:
          _09_ = 4'hd;
      /* src = "clk_generator_e.v:68" */
      4'hd:
          _09_ = 4'he;
      /* src = "clk_generator_e.v:69" */
      4'he:
          _09_ = 4'hf;
      /* src = "clk_generator_e.v:70" */
      4'hf:
        begin
          _09_ = 4'h0;
          (* src = "clk_generator_e.v:73" *)
          casez (clk_f_c)
            /* src = "clk_generator_e.v:74" */
            1'h0:
                _08_ = 1'h1;
            /* src = "clk_generator_e.v:75" */
            1'h1:
                _08_ = 1'h0;
            default:
                /* empty */;
          endcase
        end
      default:
          /* empty */;
    endcase
  end
  always @(posedge clk_32f) begin
      clk_2f_e <= _06_;
      clk_4f_e <= _07_;
      clk_f_c <= _08_;
      conteo_4 <= _11_;
      conteo_2 <= _10_;
      conteo <= _09_;
  end
endmodule

(* src = "parallel_serial_e.v:1" *)
module parallel_serial_e(clk_32f, reset, valid_in, Data_in, Data_out_e);
  (* src = "parallel_serial_e.v:11" *)
  reg _0_;
  (* src = "parallel_serial_e.v:11" *)
  reg [2:0] _1_;
  (* src = "parallel_serial_e.v:11" *)
  reg [7:0] _2_;
  (* src = "parallel_serial_e.v:19" *)
  reg _3_;
  (* src = "parallel_serial_e.v:19" *)
  reg [2:0] _4_;
  (* src = "parallel_serial_e.v:19" *)
  reg [7:0] _5_;
  (* src = "parallel_serial_e.v:12" *)
  wire _6_;
  (* src = "parallel_serial_e.v:5" *)
  input [7:0] Data_in;
  (* src = "parallel_serial_e.v:6" *)
  output Data_out_e;
  reg Data_out_e;
  (* src = "parallel_serial_e.v:2" *)
  input clk_32f;
  (* src = "parallel_serial_e.v:9" *)
  reg [2:0] contador;
  (* src = "parallel_serial_e.v:8" *)
  reg [7:0] data2send;
  (* src = "parallel_serial_e.v:3" *)
  input reset;
  (* src = "parallel_serial_e.v:4" *)
  input valid_in;
  assign _6_ = ~(* src = "parallel_serial_e.v:12" *) reset;
  always @* begin
    _1_ = contador;
    _0_ = Data_out_e;
    _2_ = data2send;
    (* src = "parallel_serial_e.v:12" *)
    casez (_6_)
      /* src = "parallel_serial_e.v:12" */
      1'h1:
        begin
          _0_ = 1'h0;
          _2_ = 8'hbc;
          _1_ = 3'h0;
        end
      default:
          /* empty */;
    endcase
  end
  always @* begin
      contador <= _1_;
      Data_out_e <= _0_;
      data2send <= _2_;
  end
  always @* begin
    _4_ = contador;
    _3_ = Data_out_e;
    _5_ = data2send;
    (* src = "parallel_serial_e.v:20" *)
    casez (contador)
      /* src = "parallel_serial_e.v:21" */
      3'h0:
        begin
          _3_ = data2send[7];
          _4_ = 3'h1;
        end
      /* src = "parallel_serial_e.v:26" */
      3'h1:
        begin
          _3_ = data2send[6];
          _4_ = 3'h2;
        end
      /* src = "parallel_serial_e.v:31" */
      3'h2:
        begin
          _3_ = data2send[5];
          _4_ = 3'h3;
        end
      /* src = "parallel_serial_e.v:36" */
      3'h3:
        begin
          _3_ = data2send[4];
          _4_ = 3'h4;
        end
      /* src = "parallel_serial_e.v:41" */
      3'h4:
        begin
          _3_ = data2send[3];
          _4_ = 3'h5;
        end
      /* src = "parallel_serial_e.v:46" */
      3'h5:
        begin
          _3_ = data2send[2];
          _4_ = 3'h6;
        end
      /* src = "parallel_serial_e.v:51" */
      3'h6:
        begin
          _3_ = data2send[1];
          _4_ = 3'h7;
        end
      /* src = "parallel_serial_e.v:56" */
      3'h7:
        begin
          _3_ = data2send[0];
          _4_ = 3'h0;
          (* src = "parallel_serial_e.v:60" *)
          casez (valid_in)
            /* src = "parallel_serial_e.v:60" */
            1'h1:
                _5_ = Data_in;
            /* src = "parallel_serial_e.v:61" */
            default:
                _5_ = 8'hbc;
          endcase
        end
      default:
          /* empty */;
    endcase
  end
  always @(posedge clk_32f) begin
      contador <= _4_;
      Data_out_e <= _3_;
      data2send <= _5_;
  end
endmodule

(* top =  1  *)
(* src = "phy_e.v:5" *)
module phy_e(clk_32f, reset, valid_in, Data_in, valid_out_e, Data_out_e);
  (* src = "phy_e.v:53" *)
  reg [31:0] _0_;
  (* src = "phy_e.v:53" *)
  reg _1_;
  (* src = "phy_e.v:16" *)
  wire [31:0] Data;
  (* src = "phy_e.v:9" *)
  input [31:0] Data_in;
  (* src = "phy_e.v:14" *)
  wire Data_out_1bit_0_c;
  (* src = "phy_e.v:15" *)
  wire Data_out_1bit_1_c;
  (* src = "phy_e.v:11" *)
  output [31:0] Data_out_e;
  reg [31:0] Data_out_e;
  (* src = "phy_e.v:26" *)
  wire clk_2f_e;
  (* src = "phy_e.v:6" *)
  input clk_32f;
  (* src = "phy_e.v:27" *)
  wire clk_4f_e;
  (* src = "phy_e.v:36" *)
  wire clk_f_c;
  (* src = "phy_e.v:7" *)
  input reset;
  (* src = "phy_e.v:17" *)
  wire valid;
  (* src = "phy_e.v:8" *)
  input valid_in;
  (* src = "phy_e.v:10" *)
  output valid_out_e;
  reg valid_out_e;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_e.v:32" *)
  clk_generator_e clk_generador (
    .clk_2f_e(clk_2f_e),
    .clk_32f(clk_32f),
    .clk_4f_e(clk_4f_e),
    .clk_f_c(clk_f_c),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_e.v:41" *)
  phy_rx_e phy_rx_c00 (
    .Data_in_0(Data_out_1bit_0_c),
    .Data_in_1(Data_out_1bit_1_c),
    .Data_out_e(Data),
    .clk_2f_e(clk_2f_e),
    .clk_32f(clk_32f),
    .clk_4f_e(clk_4f_e),
    .reset(reset),
    .valid_out_e(valid)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_e.v:19" *)
  phy_tx_e phy_tx_c00 (
    .Data_in(Data_in),
    .Data_out_1bit_0_c(Data_out_1bit_0_c),
    .Data_out_1bit_1_c(Data_out_1bit_1_c),
    .clk_2f_e(clk_2f_e),
    .clk_32f(clk_32f),
    .clk_4f_e(clk_4f_e),
    .reset(reset),
    .valid_in(valid_in)
  );
  always @* begin
    _1_ = valid;
    _0_ = Data;
  end
  always @* begin
      valid_out_e <= _1_;
      Data_out_e <= _0_;
  end
endmodule

(* src = "phy_rx_e.v:5" *)
module phy_rx_e(clk_32f, clk_2f_e, clk_4f_e, reset, Data_in_0, Data_in_1, valid_out_e, Data_out_e);
  (* src = "phy_rx_e.v:30" *)
  reg [31:0] _0_;
  (* src = "phy_rx_e.v:30" *)
  reg _1_;
  (* src = "phy_rx_e.v:28" *)
  wire [31:0] Data_c;
  (* src = "phy_rx_e.v:10" *)
  input Data_in_0;
  (* src = "phy_rx_e.v:11" *)
  input Data_in_1;
  (* src = "phy_rx_e.v:24" *)
  wire [7:0] Data_out_0_c;
  (* src = "phy_rx_e.v:26" *)
  wire [7:0] Data_out_1_c;
  (* src = "phy_rx_e.v:13" *)
  output [31:0] Data_out_e;
  reg [31:0] Data_out_e;
  (* src = "phy_rx_e.v:7" *)
  input clk_2f_e;
  (* src = "phy_rx_e.v:6" *)
  input clk_32f;
  (* src = "phy_rx_e.v:8" *)
  input clk_4f_e;
  (* src = "phy_rx_e.v:20" *)
  wire [31:0] lane_0_c;
  (* src = "phy_rx_e.v:22" *)
  wire [31:0] lane_1_c;
  (* src = "phy_rx_e.v:9" *)
  input reset;
  (* src = "phy_rx_e.v:19" *)
  wire valid_0_c;
  (* src = "phy_rx_e.v:21" *)
  wire valid_1_c;
  (* src = "phy_rx_e.v:27" *)
  wire valid_c;
  (* src = "phy_rx_e.v:23" *)
  wire valid_out_0_c;
  (* src = "phy_rx_e.v:25" *)
  wire valid_out_1_c;
  (* src = "phy_rx_e.v:12" *)
  output valid_out_e;
  reg valid_out_e;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_e.v:53" *)
  bits8_32word_e bits8_32word_1 (
    .Data_in(Data_out_0_c),
    .Data_out_e(lane_0_c),
    .clk_4f_e(clk_4f_e),
    .reset(reset),
    .valid_in(valid_out_0_c),
    .valid_out_e(valid_0_c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_e.v:63" *)
  bits8_32word_e bits8_32word_2 (
    .Data_in(Data_out_1_c),
    .Data_out_e(lane_1_c),
    .clk_4f_e(clk_4f_e),
    .reset(reset),
    .valid_in(valid_out_1_c),
    .valid_out_e(valid_1_c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_e.v:73" *)
  byte_un_striping_e byte_un_striping_1 (
    .Data_out_e(Data_c),
    .clk_2f_e(clk_2f_e),
    .lane_0(lane_0_c),
    .lane_1(lane_1_c),
    .reset(reset),
    .valid_0(valid_0_c),
    .valid_1(valid_1_c),
    .valid_out_e(valid_c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_e.v:35" *)
  serial_parallel_e serial_parallel_1 (
    .Data_in(Data_in_0),
    .Data_out_e(Data_out_0_c),
    .clk_32f(clk_32f),
    .reset(reset),
    .valid_out_e(valid_out_0_c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_e.v:44" *)
  serial_parallel_e serial_parallel_2 (
    .Data_in(Data_in_1),
    .Data_out_e(Data_out_1_c),
    .clk_32f(clk_32f),
    .reset(reset),
    .valid_out_e(valid_out_1_c)
  );
  always @* begin
    _1_ = valid_c;
    _0_ = Data_c;
  end
  always @* begin
      valid_out_e <= _1_;
      Data_out_e <= _0_;
  end
endmodule

(* src = "phy_tx_e.v:5" *)
module phy_tx_e(clk_32f, clk_2f_e, clk_4f_e, reset, valid_in, Data_in, Data_out_1bit_0_c, Data_out_1bit_1_c);
  (* src = "phy_tx_e.v:30" *)
  reg _0_;
  (* src = "phy_tx_e.v:30" *)
  reg _1_;
  (* src = "phy_tx_e.v:11" *)
  input [31:0] Data_in;
  (* src = "phy_tx_e.v:24" *)
  wire [7:0] Data_out_0_c;
  (* src = "phy_tx_e.v:26" *)
  wire [7:0] Data_out_1_c;
  (* src = "phy_tx_e.v:12" *)
  output Data_out_1bit_0_c;
  reg Data_out_1bit_0_c;
  (* src = "phy_tx_e.v:13" *)
  output Data_out_1bit_1_c;
  reg Data_out_1bit_1_c;
  (* src = "phy_tx_e.v:27" *)
  wire Out_0_c;
  (* src = "phy_tx_e.v:28" *)
  wire Out_1_c;
  (* src = "phy_tx_e.v:7" *)
  input clk_2f_e;
  (* src = "phy_tx_e.v:6" *)
  input clk_32f;
  (* src = "phy_tx_e.v:8" *)
  input clk_4f_e;
  (* src = "phy_tx_e.v:20" *)
  wire [31:0] lane_0_c;
  (* src = "phy_tx_e.v:22" *)
  wire [31:0] lane_1_c;
  (* src = "phy_tx_e.v:9" *)
  input reset;
  (* src = "phy_tx_e.v:19" *)
  wire valid_0_c;
  (* src = "phy_tx_e.v:21" *)
  wire valid_1_c;
  (* src = "phy_tx_e.v:10" *)
  input valid_in;
  (* src = "phy_tx_e.v:23" *)
  wire valid_out_0_c;
  (* src = "phy_tx_e.v:25" *)
  wire valid_out_1_c;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_e.v:35" *)
  byte_striping_e byte_striping_1 (
    .Data_in(Data_in),
    .clk_2f_e(clk_2f_e),
    .lane_0_c(lane_0_c),
    .lane_1_c(lane_1_c),
    .reset(reset),
    .valid_0_c(valid_0_c),
    .valid_1_c(valid_1_c),
    .valid_in(valid_in)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_e.v:70" *)
  parallel_serial_e parallel_serial_e1 (
    .Data_in(Data_out_0_c),
    .Data_out_e(Out_0_c),
    .clk_32f(clk_32f),
    .reset(reset),
    .valid_in(valid_out_0_c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_e.v:80" *)
  parallel_serial_e parallel_serial_e2 (
    .Data_in(Data_out_1_c),
    .Data_out_e(Out_1_c),
    .clk_32f(clk_32f),
    .reset(reset),
    .valid_in(valid_out_1_c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_e.v:48" *)
  word32_8bits_e word32_8bits_1 (
    .Data_in(lane_0_c),
    .Data_out_e(Data_out_0_c),
    .clk_4f_e(clk_4f_e),
    .reset(reset),
    .valid_in(valid_0_c),
    .valid_out_e(valid_out_0_c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_e.v:59" *)
  word32_8bits_e word32_8bits_2 (
    .Data_in(lane_1_c),
    .Data_out_e(Data_out_1_c),
    .clk_4f_e(clk_4f_e),
    .reset(reset),
    .valid_in(valid_1_c),
    .valid_out_e(valid_out_1_c)
  );
  always @* begin
    _0_ = Out_0_c;
    _1_ = Out_1_c;
  end
  always @* begin
      Data_out_1bit_0_c <= _0_;
      Data_out_1bit_1_c <= _1_;
  end
endmodule

(* src = "serial_parallel_e.v:1" *)
module serial_parallel_e(clk_32f, reset, Data_in, valid_out_e, Data_out_e);
  (* src = "serial_parallel_e.v:13" *)
  reg [1:0] _00_;
  (* src = "serial_parallel_e.v:13" *)
  reg [7:0] _01_;
  (* src = "serial_parallel_e.v:13" *)
  reg _02_;
  (* src = "serial_parallel_e.v:13" *)
  reg [2:0] _03_;
  (* src = "serial_parallel_e.v:13" *)
  reg [7:0] _04_;
  (* src = "serial_parallel_e.v:13" *)
  reg _05_;
  (* src = "serial_parallel_e.v:24" *)
  reg [1:0] _06_;
  (* src = "serial_parallel_e.v:24" *)
  reg [7:0] _07_;
  (* src = "serial_parallel_e.v:24" *)
  reg _08_;
  (* src = "serial_parallel_e.v:24" *)
  reg [2:0] _09_;
  (* src = "serial_parallel_e.v:24" *)
  reg [7:0] _10_;
  (* src = "serial_parallel_e.v:24" *)
  reg _11_;
  wire [3:0] _12_;
  wire [1:0] _13_;
  wire _14_;
  wire [7:0] _15_;
  wire _16_;
  (* src = "serial_parallel_e.v:14" *)
  wire _17_;
  (* src = "serial_parallel_e.v:29" *)
  wire _18_;
  (* src = "serial_parallel_e.v:81" *)
  wire _19_;
  (* src = "serial_parallel_e.v:10" *)
  reg [1:0] BC_count;
  (* src = "serial_parallel_e.v:4" *)
  input Data_in;
  (* src = "serial_parallel_e.v:6" *)
  output [7:0] Data_out_e;
  reg [7:0] Data_out_e;
  (* src = "serial_parallel_e.v:11" *)
  reg active;
  (* src = "serial_parallel_e.v:2" *)
  input clk_32f;
  (* src = "serial_parallel_e.v:9" *)
  reg [2:0] contador;
  (* src = "serial_parallel_e.v:8" *)
  reg [7:0] memoria;
  (* src = "serial_parallel_e.v:3" *)
  input reset;
  (* src = "serial_parallel_e.v:5" *)
  output valid_out_e;
  reg valid_out_e;
  assign _16_ = _13_[0] |(* src = "serial_parallel_e.v:81" *)  _13_[1];
  assign _12_[0] = _15_[0] |(* src = "serial_parallel_e.v:81" *)  _15_[1];
  assign _12_[1] = _15_[2] |(* src = "serial_parallel_e.v:81" *)  _15_[3];
  assign _12_[2] = _15_[4] |(* src = "serial_parallel_e.v:81" *)  _15_[5];
  assign _12_[3] = _15_[6] |(* src = "serial_parallel_e.v:81" *)  _15_[7];
  assign _13_[0] = _12_[0] |(* src = "serial_parallel_e.v:81" *)  _12_[1];
  assign _13_[1] = _12_[2] |(* src = "serial_parallel_e.v:81" *)  _12_[3];
  assign _19_ = ~(* src = "serial_parallel_e.v:81" *) _16_;
  assign _17_ = ~(* src = "serial_parallel_e.v:14" *) reset;
  assign _15_[2] = memoria[2] ^(* src = "serial_parallel_e.v:81" *)  1'h1;
  assign _15_[3] = memoria[3] ^(* src = "serial_parallel_e.v:81" *)  1'h1;
  assign _15_[4] = memoria[4] ^(* src = "serial_parallel_e.v:81" *)  1'h1;
  assign _15_[5] = memoria[5] ^(* src = "serial_parallel_e.v:81" *)  1'h1;
  assign _15_[7] = memoria[7] ^(* src = "serial_parallel_e.v:81" *)  1'h1;
  always @* begin
    _03_ = contador;
    _05_ = valid_out_e;
    _01_ = Data_out_e;
    _04_ = memoria;
    _00_ = BC_count;
    _02_ = active;
    (* src = "serial_parallel_e.v:14" *)
    casez (_17_)
      /* src = "serial_parallel_e.v:14" */
      1'h1:
        begin
          _05_ = 1'h0;
          _01_ = 8'h00;
          _04_ = 8'h00;
          _03_ = 3'h7;
          _00_ = 2'h0;
          _02_ = 1'h0;
        end
      default:
          /* empty */;
    endcase
  end
  always @* begin
      contador <= _03_;
      valid_out_e <= _05_;
      Data_out_e <= _01_;
      memoria <= _04_;
      BC_count <= _00_;
      active <= _02_;
  end
  always @* begin
    _09_ = contador;
    _11_ = valid_out_e;
    _07_ = Data_out_e;
    _10_ = memoria;
    _06_ = BC_count;
    _08_ = active;
    (* src = "serial_parallel_e.v:25" *)
    casez (active)
      /* src = "serial_parallel_e.v:25" */
      1'h1:
          (* src = "serial_parallel_e.v:26" *)
          casez (contador)
            /* src = "serial_parallel_e.v:27" */
            3'h0:
              begin
                _09_ = 3'h1;
                _10_ = { Data_in, 7'h00 };
                (* src = "serial_parallel_e.v:29" *)
                casez (_18_)
                  /* src = "serial_parallel_e.v:29" */
                  1'h1:
                    begin
                      _11_ = 1'h0;
                      _07_ = 8'h00;
                    end
                  /* src = "serial_parallel_e.v:33" */
                  default:
                    begin
                      _11_ = 1'h1;
                      _07_ = memoria;
                    end
                endcase
              end
            /* src = "serial_parallel_e.v:40" */
            3'h1:
              begin
                _09_ = 3'h2;
                _10_ = { memoria[7], Data_in, 6'h00 };
              end
            /* src = "serial_parallel_e.v:45" */
            3'h2:
              begin
                _09_ = 3'h3;
                _10_ = { memoria[7:6], Data_in, 5'h00 };
              end
            /* src = "serial_parallel_e.v:50" */
            3'h3:
              begin
                _09_ = 3'h4;
                _10_ = { memoria[7:5], Data_in, 4'h0 };
              end
            /* src = "serial_parallel_e.v:55" */
            3'h4:
              begin
                _09_ = 3'h5;
                _10_ = { memoria[7:4], Data_in, 3'h0 };
              end
            /* src = "serial_parallel_e.v:60" */
            3'h5:
              begin
                _09_ = 3'h6;
                _10_ = { memoria[7:3], Data_in, 2'h0 };
              end
            /* src = "serial_parallel_e.v:65" */
            3'h6:
              begin
                _09_ = 3'h7;
                _10_ = { memoria[7:2], Data_in, 1'h0 };
              end
            /* src = "serial_parallel_e.v:70" */
            3'h7:
              begin
                _09_ = 3'h0;
                _10_ = { memoria[7:1], Data_in };
              end
            default:
                /* empty */;
          endcase
      /* src = "serial_parallel_e.v:77" */
      default:
          (* src = "serial_parallel_e.v:78" *)
          casez (contador)
            /* src = "serial_parallel_e.v:79" */
            3'h0:
              begin
                _09_ = 3'h1;
                _10_ = { Data_in, 7'h00 };
                (* src = "serial_parallel_e.v:81" *)
                casez (_19_)
                  /* src = "serial_parallel_e.v:81" */
                  1'h1:
                      (* src = "serial_parallel_e.v:82" *)
                      casez (BC_count)
                        /* src = "serial_parallel_e.v:83" */
                        2'h0:
                            _06_ = 2'h1;
                        /* src = "serial_parallel_e.v:84" */
                        2'h1:
                            _06_ = 2'h2;
                        /* src = "serial_parallel_e.v:85" */
                        2'h2:
                            _06_ = 2'h3;
                        /* src = "serial_parallel_e.v:86" */
                        2'h3:
                            _08_ = 1'h1;
                        default:
                            /* empty */;
                      endcase
                  default:
                      /* empty */;
                endcase
              end
            /* src = "serial_parallel_e.v:92" */
            3'h1:
              begin
                _09_ = 3'h2;
                _10_ = { memoria[7], Data_in, 6'h00 };
              end
            /* src = "serial_parallel_e.v:97" */
            3'h2:
              begin
                _09_ = 3'h3;
                _10_ = { memoria[7:6], Data_in, 5'h00 };
              end
            /* src = "serial_parallel_e.v:102" */
            3'h3:
              begin
                _09_ = 3'h4;
                _10_ = { memoria[7:5], Data_in, 4'h0 };
              end
            /* src = "serial_parallel_e.v:107" */
            3'h4:
              begin
                _09_ = 3'h5;
                _10_ = { memoria[7:4], Data_in, 3'h0 };
              end
            /* src = "serial_parallel_e.v:112" */
            3'h5:
              begin
                _09_ = 3'h6;
                _10_ = { memoria[7:3], Data_in, 2'h0 };
              end
            /* src = "serial_parallel_e.v:117" */
            3'h6:
              begin
                _09_ = 3'h7;
                _10_ = { memoria[7:2], Data_in, 1'h0 };
              end
            /* src = "serial_parallel_e.v:122" */
            3'h7:
              begin
                _09_ = 3'h0;
                _10_ = { memoria[7:1], Data_in };
              end
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk_32f) begin
      contador <= _09_;
      valid_out_e <= _11_;
      Data_out_e <= _07_;
      memoria <= _10_;
      BC_count <= _06_;
      active <= _08_;
  end
  assign _18_ = _19_;
  assign _15_[6] = memoria[6];
  assign _15_[0] = memoria[0];
  assign _15_[1] = memoria[1];
endmodule

(* src = "word32_8bits_e.v:1" *)
module word32_8bits_e(clk_4f_e, reset, valid_in, Data_in, valid_out_e, Data_out_e);
  (* src = "word32_8bits_e.v:11" *)
  reg [7:0] _0_;
  (* src = "word32_8bits_e.v:11" *)
  reg [1:0] _1_;
  (* src = "word32_8bits_e.v:11" *)
  reg _2_;
  (* src = "word32_8bits_e.v:19" *)
  reg [7:0] _3_;
  (* src = "word32_8bits_e.v:19" *)
  reg [1:0] _4_;
  (* src = "word32_8bits_e.v:19" *)
  reg _5_;
  (* src = "word32_8bits_e.v:12" *)
  wire _6_;
  (* src = "word32_8bits_e.v:5" *)
  input [31:0] Data_in;
  (* src = "word32_8bits_e.v:7" *)
  output [7:0] Data_out_e;
  reg [7:0] Data_out_e;
  (* src = "word32_8bits_e.v:2" *)
  input clk_4f_e;
  (* src = "word32_8bits_e.v:9" *)
  reg [1:0] contador;
  (* src = "word32_8bits_e.v:3" *)
  input reset;
  (* src = "word32_8bits_e.v:4" *)
  input valid_in;
  (* src = "word32_8bits_e.v:6" *)
  output valid_out_e;
  reg valid_out_e;
  assign _6_ = ~(* src = "word32_8bits_e.v:12" *) reset;
  always @* begin
    _1_ = contador;
    _2_ = valid_out_e;
    _0_ = Data_out_e;
    (* src = "word32_8bits_e.v:12" *)
    casez (_6_)
      /* src = "word32_8bits_e.v:12" */
      1'h1:
        begin
          _1_ = 2'h0;
          _2_ = 1'h0;
          _0_ = 8'h00;
        end
      default:
          /* empty */;
    endcase
  end
  always @* begin
      contador <= _1_;
      valid_out_e <= _2_;
      Data_out_e <= _0_;
  end
  always @* begin
    _4_ = contador;
    _5_ = valid_out_e;
    _3_ = Data_out_e;
    (* src = "word32_8bits_e.v:20" *)
    casez (valid_in)
      /* src = "word32_8bits_e.v:20" */
      1'h1:
          (* src = "word32_8bits_e.v:21" *)
          casez (contador)
            /* src = "word32_8bits_e.v:22" */
            2'h0:
              begin
                _3_ = Data_in[31:24];
                _4_ = 2'h1;
                _5_ = 1'h1;
              end
            /* src = "word32_8bits_e.v:28" */
            2'h1:
              begin
                _3_ = Data_in[23:16];
                _4_ = 2'h2;
                _5_ = 1'h1;
              end
            /* src = "word32_8bits_e.v:34" */
            2'h2:
              begin
                _3_ = Data_in[15:8];
                _4_ = 2'h3;
                _5_ = 1'h1;
              end
            /* src = "word32_8bits_e.v:40" */
            2'h3:
              begin
                _3_ = Data_in[7:0];
                _4_ = 2'h0;
                _5_ = 1'h1;
              end
            default:
                /* empty */;
          endcase
      /* src = "word32_8bits_e.v:48" */
      default:
        begin
          _4_ = 2'h0;
          _5_ = 1'h0;
          _3_ = 8'h00;
        end
    endcase
  end
  always @(posedge clk_4f_e) begin
      contador <= _4_;
      valid_out_e <= _5_;
      Data_out_e <= _3_;
  end
endmodule
